package by.gto.erip.model;
// Generated 16.01.2016 11:51:00 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * RefVersions generated by hbm2java
 */
@Entity
@Table(name = "ref_version", catalog = "erip")
public class RefVersion implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -2316340870493560138L;
    private String tableName;
    private int version;

    public RefVersion() {
    }

    public RefVersion(String tableName) {
        this.tableName = tableName;
    }

    @Id
    @Column(name = "table_name", unique = true, nullable = false, length = 100)
    public String getTableName() {
        return this.tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    @Version
    @Column(name = "version", nullable = false)
    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }
}
