package by.gto.erip.model;
// Generated 03.03.2016 10:55:15 by Hibernate Tools 4.3.1.Final

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

/**
 * RegisteredPayments generated by hbm2java
 */
@Entity
@Table(name = "registered_payment")
public class RegisteredPayment implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 7532504294494250110L;
    private Long id;
    private Date date;
    private BigDecimal amount;
    private String name;
    private Integer unp;
    private short serviceId;
    private byte legalType;
    private String certNumber;

    public RegisteredPayment() {
    }

    public RegisteredPayment(long id) {
        this.id = id;
    }

    public RegisteredPayment(Date date, BigDecimal amount, String name, int unp) {
        this.date = date;
        this.amount = amount;
        this.name = name;
        this.unp = unp;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "date")
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "amount", precision = 16)
    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    @Column(name = "name", length = 90)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "unp", nullable = true)
    public Integer getUnp() {
        return this.unp;
    }

    public void setUnp(Integer unp) {
        this.unp = unp;
    }

    @Column(name = "legal_type")
    public byte getLegalType() {
        return this.legalType;
    }

    public void setLegalType(byte legalType) {
        this.legalType = legalType;
    }

    @Column(name = "service_id")
    public short getServiceId() {
        return this.serviceId;
    }

    public void setServiceId(short serviceId) {
        this.serviceId = serviceId;
    }

    @Column(name = "cert_number", nullable = true)
    public String getCertNumber() {
        return certNumber;
    }

    public void setCertNumber(String certNumber) {
        this.certNumber = certNumber;
    }
}
